### ISSUE TITLE
line fit 

### ISSUE THREAD

**Issue by AliAshrafRagab** [udacity/CarND-LaneLines-P1#73]
Traceback (most recent call last):
  File "C:\Users\Ali\Desktop\Lane Detection\Line_Fit\line_fit_video.py", line 114, in <module>
    annotate_video('project_video.mp4', 'out.mp4')
  File "C:\Users\Ali\Desktop\Lane Detection\Line_Fit\line_fit_video.py", line 108, in annotate_video
    annotated_video = video.fl_image(annotate_image)
  File "C:\Python27\lib\site-packages\moviepy\video\VideoClip.py", line 533, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "C:\Python27\lib\site-packages\moviepy\Clip.py", line 136, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-57>", line 2, in set_make_frame
  File "C:\Python27\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Python27\lib\site-packages\moviepy\video\VideoClip.py", line 694, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-14>", line 2, in get_frame
  File "C:\Python27\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Python27\lib\site-packages\moviepy\Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "C:\Python27\lib\site-packages\moviepy\Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Python27\lib\site-packages\moviepy\video\VideoClip.py", line 533, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "C:\Users\Ali\Desktop\Lane Detection\Line_Fit\line_fit_video.py", line 66, in annotate_image
    left_curve, right_curve = calc_curve(left_lane_inds, right_lane_inds, nonzerox, nonzeroy)
  File "C:\Users\Ali\Desktop\Lane Detection\Line_Fit\line_fit.py", line 241, in calc_curve
    left_fit_cr = np.polyfit(lefty*ym_per_pix, leftx*xm_per_pix, 2)
  File "C:\Python27\lib\site-packages\numpy\lib\polynomial.py", line 588, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "C:\Python27\lib\site-packages\numpy\linalg\linalg.py", line 1921, in lstsq
    raise LinAlgError('SVD did not converge in Linear Least Squares')
LinAlgError: SVD did not converge in Linear Least Squares

**Comment by mvirgo** [comment]
Hi there! It's a little tough to tell without seeing the rest of the code, but this typically gets thrown when there wasn't a lane line detection during the processing of the image (most likely the polyfit function got fed an empty array of pixels). 

What you might consider doing is using a counter somehow to check where in the video you are when it fails, and try your pipeline on the specific frame(s) in question to see what the issue may be.

**Comment by mvirgo** [comment]
Closing based on thumb's up and no further follow-ups :)
